export const rsvpData = {
  "raymond li": ["Yes", "Yes", "10oz Filet Mignon"],
  "yi-nung huang": ["Yes", "Yes", "Chilean Sea Bass"],
  "linda li": ["Yes", "Yes", "Wild Mushroom Ravioli"],
  "jakub woyke": ["Yes", "Yes", "Chilean Sea Bass"],
  "wanjing xu": ["Yes", "Yes", "Chilean Sea Bass"],
  "fayu li": ["Yes", "Yes", "Jidori Roasted Chicken"],
  "yoonhee choi": ["Yes", "Yes", "10oz Filet Mignon"],
  "yusuke kikuchi": ["Yes", "Yes", "10oz Filet Mignon"],
  "wei li": ["No", "No", "N/A"],
  "shuya zhan": ["Yes", "Yes", "10oz Filet Mignon"],
  "haoran zhang": ["Yes", "Yes", "Chilean Sea Bass"],
  "anthony liu": ["Yes", "Yes", "Chilean Sea Bass"],
  "mahal miles": ["Yes", "Yes", "Chilean Sea Bass"],
  "ye eun hong": ["Yes", "Yes", "10oz Filet Mignon"],
  "kenny ashley": ["Yes", "Yes", "Chilean Sea Bass"],
  "alyssa ashley": ["Yes", "Yes", "10oz Filet Mignon"],
  "eva mo": ["Yes", "Yes", "10oz Filet Mignon"],
  "shellen su": ["Yes", "Yes", "10oz Filet Mignon"],
  "ysabelle lam": ["Yes", "Yes", "Chilean Sea Bass"],
  "kevin huang": ["Yes", "Yes", "10oz Filet Mignon"],
  "noah hashmi": ["Yes", "Yes", "Wild Mushroom Ravioli"],
  葉美華: ["是", "是", "10 盎司菲力牛排"],
  黃俊彥: ["是", "是", "10 盎司菲力牛排"],
  "alice chou": ["Yes", "Yes", "Chilean Sea Bass"],
  "aaron hsu": ["Yes", "Yes", "10oz Filet Mignon"],
  "yun ding": ["Yes", "Yes", "Chilean Sea Bass"],
  "chia-hua chang": ["是", "是", "智利鱸魚"],
  "dingyi shen": ["Yes", "Yes", "10oz Filet Mignon"],
  "andong jing": ["Yes", "Yes", "Jidori Roasted Chicken"],
  "melody chao": ["Yes", "Yes", "10oz Filet Mignon"],
  "eric wang": ["Yes", "Yes", "Chilean Sea Bass"],
  黃思嘉: ["是", "是", "10 盎司菲力牛排"],
  "weichen lin": ["是", "是", "智利鱸魚"],
  徐万盾: ["是", "是", "智利鱸魚"],
  "alec deng": ["Yes", "Yes", "Chilean Sea Bass"],
  "ryan shim": ["Yes", "Yes", "10oz Filet Mignon"],
  "crystal nguyen": ["Yes", "Yes", "Wild Mushroom Ravioli"],
  "sung joon baek": ["Yes", "Yes", "10oz Filet Mignon"],
  "ha nguyen": ["Yes", "Yes", "Wild Mushroom Ravioli"],
  "wesley woo": ["Yes", "Yes", "Chilean Sea Bass"],
  "chloe lee": ["Yes", "Yes", "Chilean Sea Bass"],
  "hank lee": ["Yes", "Yes", "10oz Filet Mignon"],
};
